### PR TITLE
Hostname as array

### LINKED ISSUE #2: Cassandra driver expects hostname to be an array.
If the in the `database.json` configuration the `host` name is left out or taken from the environment (using for example `{"ENV": "CASSANDRA_HOSTNAME"}`) then any migration fails because `hostname` for the cassandra driver is not set correctly.

It would be nice if the hostname would be treated as a comma separated list of hosts, too. Which makes it possible to configure several host names using an environment variable.

### PR DESCRIPTION
**Pull request by merry-bits**
- fixes #2

### CODE REVIEW

**Comment by ramakrishnan** [comment]
@merry-bits Can you add a test case for this change.

**Comment by merry-bits** [comment]
Here you go. Did not write JS tests lately. I hope they are adequate.

File: index.js [hunk 1]
```diff
@@ -228,10 +231,10 @@ exports.connect = function(config, intern, callback) {
     host = config.host;
   }
 
-  if(config.port === undefined) {
-    port = 9160;
-  } else {
-    port = config.port;
```
Comment (ramakrishnan) [inline index.js:238]: Does Cassandra takes port number by default?

File: index.js [hunk 2]
```diff
@@ -44,6 +44,10 @@ var CqlshDriver = Base.extend({
     metaData.push('PRIMARY KEY ' + primaryKey);
     cql.push(metaData.join(', '));
     cql.push(')');
+    if (constraints.compression) {
+      cql.push('WITH compression =');
+      cql.push(constraints.compression);
+    }
```
Comment (ramakrishnan) [inline index.js:50]: There is a separate pull request for this change, can you remove this from this pull request.

**Review by ramakrishnan — CHANGES_REQUESTED** [review]
Most of the changes looks good, can you please address the review comments.

File: index.js (hunk 1 above)
Comment (merry-bits) [reply index.js:238]: Well, first, I removed this code, because the `port` variable was not used anywhere after those lines... And, second, the Cassandra driver does not have a port parameter as such. Instead you can specify the port together with the host, like `127.0.0.1:9042`.
So, it is in fact not exactly possible nor convenient to have one single port parameter.

File: index.js (hunk 2 above)
Comment (merry-bits) [reply index.js:50]: You mean the commit `ee6c71b540cf28b13b6dbff5815f563068afac93`, right? I think the pull request that you refer to is part of this here pull request, already. So if you merge the other pull request first, and refresh this one, the above (changed) lines should not show up anymore. Does that make sense?

**Review by merry-bits — COMMENTED** [review]
Thank you for paying attention to the pull request :)

File: index.js (hunk 2 above)
Comment (ramakrishnan) [reply index.js:50]: I merged the other pull request and this shows conflict. Can you resolve the conflict

**Review by ramakrishnan — CHANGES_REQUESTED** [review]
Can you please fix the conflict.
